name: dmproj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - missingno
  - pillow
  - ipykernel
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - tornado
  - traitlets
  - pip
  - pyzmq
  - prompt-toolkit
  - typing_extensions
  - setuptools
  - wheel
  - zlib
  - tzdata
  - six
  - pexpect
  - psutil
  - decorator
  - pygments
  - jedi
  - nest-asyncio
  - bottleneck
  - numexpr
  - cycler
  - python-dateutil
  - kiwisolver
  - platformdirs
  - zipp
  - wcwidth
  - libffi
  - freetype
  - jpeg
  - lcms2
  - libtiff
  - xz
  - zstd
  - lz4-c
  - readline
  - sqlite
  - openssl
  - ca-certificates
  - libpng
  - libsodium
  - zeromq
  - tk
  - unicodedata2
  
  - pip:
      - pycountry
      - pure_eval
      - stack_data
      - platformdirs
      - exceptiongroup
      - asttokens
      - executing
      - debugpy
